### ISSUE TITLE
Are the FreeCAD folks aware of this macro?

### ISSUE THREAD

**Issue by luzpaz** [pgilfernandez/FreeCAD_AliasManager#1]
CC @eivindkv

**Comment by pgilfernandez** [comment]
I'm unsure... I know there is a listed "Alias Manager" but I don't know if it's whether mine or the original version which is simpler...

**Comment by s-light** [comment]
i first found the [forum thread](https://forum.freecadweb.org/viewtopic.php?t=18437)
there is also mentioned the [SheetProperties](https://github.com/uribench/SheetProperties) Macro.
[DeepSOIC linked](https://forum.freecadweb.org/viewtopic.php?p=251435#p251435) to the Macro-Wiki-Page that links to this repository as answer to another macro similar to this...

i have installed the `Macro Alias Manager` via the Addon-Installer.
this is coming up:
![image](https://user-images.githubusercontent.com/1340319/54128124-ac721f00-440b-11e9-9bdf-192345600628.png)
so i think this is using yours! :-)

**Comment by snelweg** [comment]
It will not install in 18.3?

**Comment by pgilfernandez** [comment]
It should install, yes
